DATABASE:
  DRIVER: "postgresql+asyncpg"
  HOST: localhost
  PORT: 5432
  IS_ECHO: no
  POOL_SIZE: 10
  MAX_OVERFLOW: 15

BROKER:
  HOST: localhost
  PORT: 5672
  PROTOCOL: amqp

MESSAGING:
  PAYMENTS:
    TOPICS:
      NEW: payments.new
      WEBHOOKS: payments.webhooks
      WEBHOOKS_DEAD: payments.webhooks.dead

LOGGING:
  FORMAT: "%(asctime)s %(levelname)s %(message)s"
  LEVEL: INFO
